server:
  port: 4000

spring:
  application:
    name: patient-service

#  datasource:
#    url: jdbc:mysql://localhost:3306/patient_service
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect
#
#  sql:
#    init:
#      mode: ALWAYS

  devtools:
    restart:
      enabled: true

logging:
  level:
    com.zaxxer.hikari: warn
    org.springframework.boot.autoconfigure.jdbc: warn
    org.hibernate.orm.connections.pooling: warn

